/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cash_app;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Assem
 */
public class Employee_services_gui extends javax.swing.JFrame {

    /**
     * Creates new form Employee_services
     */
    public Employee_services_gui() {
        initComponents();
        TableDisplay_trans_log();
        TableDisplay_currency();
    }
    private void TableDisplay_trans_log()
    {
        try
        {
            Transaction db_obj = new Transaction();
            ResultSet rs= db_obj.emp_show_trans_log();

            jTable_trans_log.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void TableDisplay_currency()
    {
        try
        {
            Currency db_obj = new Currency();
            ResultSet rs= db_obj.show_currency();

            jTable_currencies.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_modify_curr = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jButton_currency = new javax.swing.JButton();
        jTextField_code = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_buy_price = new javax.swing.JTextField();
        jTextField_sell_price = new javax.swing.JTextField();
        jButton_show_curr = new javax.swing.JButton();
        jFrame_user_data = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jButton_user_data1 = new javax.swing.JButton();
        jTextField_user_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFrame_delete_user = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jButton_delete_user1 = new javax.swing.JButton();
        jTextField_user_id2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFrame_trans_log = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_trans_log = new javax.swing.JTable();
        jFrame_currencies = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_currencies = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_modify_curr = new javax.swing.JButton();
        jButton_user_data = new javax.swing.JButton();
        jButton_delete_user = new javax.swing.JButton();
        jButton_log_out = new javax.swing.JButton();
        jButton_transaction = new javax.swing.JButton();

        jFrame_modify_curr.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame_modify_curr.setMinimumSize(new java.awt.Dimension(400, 374));
        jFrame_modify_curr.setSize(new java.awt.Dimension(400, 374));

        jButton_currency.setText("Modify Currency");
        jButton_currency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_currencyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Code");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Selling Price");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Buying Price");

        jButton_show_curr.setText("Currency Exchange Rate");
        jButton_show_curr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_currActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_sell_price, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_buy_price, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_code, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_currency, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jButton_show_curr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_buy_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_sell_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton_currency, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_show_curr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame_modify_currLayout = new javax.swing.GroupLayout(jFrame_modify_curr.getContentPane());
        jFrame_modify_curr.getContentPane().setLayout(jFrame_modify_currLayout);
        jFrame_modify_currLayout.setHorizontalGroup(
            jFrame_modify_currLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame_modify_currLayout.setVerticalGroup(
            jFrame_modify_currLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_modify_currLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFrame_user_data.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame_user_data.setMinimumSize(new java.awt.Dimension(400, 300));
        jFrame_user_data.setSize(new java.awt.Dimension(400, 300));

        jButton_user_data1.setText("Show Customer data");
        jButton_user_data1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_user_data1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Customer ID");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton_user_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50)
                        .addComponent(jTextField_user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jButton_user_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame_user_dataLayout = new javax.swing.GroupLayout(jFrame_user_data.getContentPane());
        jFrame_user_data.getContentPane().setLayout(jFrame_user_dataLayout);
        jFrame_user_dataLayout.setHorizontalGroup(
            jFrame_user_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame_user_dataLayout.setVerticalGroup(
            jFrame_user_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame_delete_user.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame_delete_user.setMinimumSize(new java.awt.Dimension(400, 300));
        jFrame_delete_user.setSize(new java.awt.Dimension(400, 300));

        jButton_delete_user1.setText("Delete Customer Account");
        jButton_delete_user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete_user1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Customer ID");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton_delete_user1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField_user_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_user_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jButton_delete_user1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame_delete_userLayout = new javax.swing.GroupLayout(jFrame_delete_user.getContentPane());
        jFrame_delete_user.getContentPane().setLayout(jFrame_delete_userLayout);
        jFrame_delete_userLayout.setHorizontalGroup(
            jFrame_delete_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame_delete_userLayout.setVerticalGroup(
            jFrame_delete_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame_trans_log.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame_trans_log.setMinimumSize(new java.awt.Dimension(697, 315));
        jFrame_trans_log.setSize(new java.awt.Dimension(697, 315));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel6.setText("Transactions log");

        jTable_trans_log.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1", "2", "3", "4"
            }
        ));
        jTable_trans_log.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTable_trans_log);

        javax.swing.GroupLayout jFrame_trans_logLayout = new javax.swing.GroupLayout(jFrame_trans_log.getContentPane());
        jFrame_trans_log.getContentPane().setLayout(jFrame_trans_logLayout);
        jFrame_trans_logLayout.setHorizontalGroup(
            jFrame_trans_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_trans_logLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jFrame_trans_logLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel6)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jFrame_trans_logLayout.setVerticalGroup(
            jFrame_trans_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_trans_logLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jFrame_currencies.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame_currencies.setMinimumSize(new java.awt.Dimension(697, 315));
        jFrame_currencies.setSize(new java.awt.Dimension(697, 315));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel7.setText("List Of Currencies");

        jTable_currencies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Currency", "Buying Price", "Selling Price"
            }
        ));
        jTable_currencies.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jTable_currencies);

        javax.swing.GroupLayout jFrame_currenciesLayout = new javax.swing.GroupLayout(jFrame_currencies.getContentPane());
        jFrame_currencies.getContentPane().setLayout(jFrame_currenciesLayout);
        jFrame_currenciesLayout.setHorizontalGroup(
            jFrame_currenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_currenciesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jFrame_currenciesLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel7)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jFrame_currenciesLayout.setVerticalGroup(
            jFrame_currenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_currenciesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jButton_modify_curr.setText("Modify Currencies");
        jButton_modify_curr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modify_currActionPerformed(evt);
            }
        });

        jButton_user_data.setText("Customer Data");
        jButton_user_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_user_dataActionPerformed(evt);
            }
        });

        jButton_delete_user.setText("Delete Customer Account");
        jButton_delete_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete_userActionPerformed(evt);
            }
        });

        jButton_log_out.setText("Log Out");
        jButton_log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_log_outActionPerformed(evt);
            }
        });

        jButton_transaction.setText("Transactions Log");
        jButton_transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_transactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton_log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_user_data, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_modify_curr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_delete_user, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(jButton_transaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton_modify_curr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_user_data, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton_log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_modify_currActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modify_currActionPerformed
        jFrame_modify_curr.setVisible(true);
        jFrame_modify_curr.setTitle("Modify Currencies");
    }//GEN-LAST:event_jButton_modify_currActionPerformed

    private void jButton_user_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_user_dataActionPerformed
        jFrame_user_data.setVisible(true);
        jFrame_user_data.setTitle("Customer Data");
    }//GEN-LAST:event_jButton_user_dataActionPerformed

    private void jButton_delete_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete_userActionPerformed
        jFrame_delete_user.setVisible(true);
        jFrame_delete_user.setTitle("Delete Customer Account");
    }//GEN-LAST:event_jButton_delete_userActionPerformed

    private void jButton_log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_log_outActionPerformed
        menu_gui menu_obj = new menu_gui();
        menu_obj.setVisible(true);
        menu_obj.setTitle("Main Menu");
        this.dispose();
    }//GEN-LAST:event_jButton_log_outActionPerformed

    private void jButton_user_data1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_user_data1ActionPerformed
        try
        {
            Employee db_obj = new Employee(); 
            String[] data = db_obj.view_customer_data(jTextField_user_id.getText());
            
            JOptionPane.showMessageDialog(this, 
                    "ID: "+data[0]+"\n"
                    +"Password: "+data[1]+"\n"
                    +"Name: "+data[2]+"\n"
                    +"Balance: "+data[3]+"\n"
                    +"Address: "+data[4]+"\n"
                    ,"Customer Data", JOptionPane.INFORMATION_MESSAGE);
            
            jFrame_user_data.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_user_data1ActionPerformed

    private void jButton_delete_user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete_user1ActionPerformed
        try
        {
            Employee db_obj = new Employee(); 
            db_obj.delete_customer(jTextField_user_id2.getText(), Employee_gui.signed_emp_id+"");
            
            JOptionPane.showMessageDialog(this, "Customer Deleted Successfully", "Customer Deleted", JOptionPane.INFORMATION_MESSAGE);
            
            jFrame_delete_user.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_delete_user1ActionPerformed

    private void jButton_currencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_currencyActionPerformed
        try
        {
            Currency db_obj = new Currency(); 
            db_obj.emp_update_currency(jTextField_code.getText(), Employee_gui.signed_emp_id+"", jTextField_buy_price.getText(), jTextField_sell_price.getText());
            
            JOptionPane.showMessageDialog(this, "Data Modified Successfully", "Currency Data", JOptionPane.INFORMATION_MESSAGE);
            jFrame_modify_curr.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_currencyActionPerformed

    private void jButton_transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_transactionActionPerformed
        TableDisplay_trans_log();
        jFrame_trans_log.setVisible(true);
        jFrame_trans_log.setTitle("Transactions log");
    }//GEN-LAST:event_jButton_transactionActionPerformed

    private void jButton_show_currActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_currActionPerformed
        TableDisplay_currency();
        jFrame_currencies.setVisible(true);
        jFrame_currencies.setTitle("Exchange Rate");
    }//GEN-LAST:event_jButton_show_currActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_services_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_services_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_services_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_services_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_services_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_currency;
    private javax.swing.JButton jButton_delete_user;
    private javax.swing.JButton jButton_delete_user1;
    private javax.swing.JButton jButton_log_out;
    private javax.swing.JButton jButton_modify_curr;
    private javax.swing.JButton jButton_show_curr;
    private javax.swing.JButton jButton_transaction;
    private javax.swing.JButton jButton_user_data;
    private javax.swing.JButton jButton_user_data1;
    private javax.swing.JFrame jFrame_currencies;
    private javax.swing.JFrame jFrame_delete_user;
    private javax.swing.JFrame jFrame_modify_curr;
    private javax.swing.JFrame jFrame_trans_log;
    private javax.swing.JFrame jFrame_user_data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_currencies;
    private javax.swing.JTable jTable_trans_log;
    private javax.swing.JTextField jTextField_buy_price;
    private javax.swing.JTextField jTextField_code;
    private javax.swing.JTextField jTextField_sell_price;
    private javax.swing.JTextField jTextField_user_id;
    private javax.swing.JTextField jTextField_user_id2;
    // End of variables declaration//GEN-END:variables
}
